// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreSystem.Data;

namespace StoreSystem.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250827235827_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreSystem.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 27, 23, 58, 27, 15, DateTimeKind.Utc).AddTicks(2020),
                            Description = "Powerful portable computer",
                            Name = "Laptop",
                            Price = 1200.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 8, 27, 23, 58, 27, 15, DateTimeKind.Utc).AddTicks(2630),
                            Description = "Wireless ergonomic mouse",
                            Name = "Mouse",
                            Price = 25.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 8, 27, 23, 58, 27, 15, DateTimeKind.Utc).AddTicks(2630),
                            Description = "Mechanical RGB keyboard",
                            Name = "Keyboard",
                            Price = 75.00m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
